services:
  node-app:
    build: .
    image: task-management-webservice
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/task-management-webservice
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/node-app
      - logs:/node-app/logs:rw
    networks:
      - node-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:
  logs:

networks:
  node-network:
    driver: bridge
